(ns readme-table
  "Generates the README's example gallery from the registry.

  The gallery is HTML rather than a markdown table because GitHub renders
  <img> inside a table cell but markdown pipe-tables cannot size an image.
  Mirrors the technique in the sibling b12n-raylib-jlt README.

  Generated, never hand-edited: the registry is the single source of truth
  for names and descriptions, and every screenshot referenced here must
  exist, so a renamed example cannot leave a broken image behind."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [examples-registry :as reg]))

(def begin-marker "<!-- BEGIN:examples (generated by `bb readme:examples`) -->")
(def end-marker "<!-- END:examples -->")

(def ^:private columns 3)

(defn- escape
  "HTML-escapes a registry description. & first, or it double-escapes."
  [s]
  (-> s
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")))

(defn demo-path
  "Screenshot path for an example, relative to the repo root."
  [name]
  (str "docs/demos/" name ".png"))

(defn missing-demos
  "Registry rows whose screenshot is absent. The drift guard: adding an example
  without committing its screenshot fails rather than shipping a broken image."
  [repo-root]
  (filterv (fn [row] (not (fs/exists? (str repo-root "/" (demo-path (nth row 0))))))
           reg/examples))

(defn- cell
  [row]
  (let [name (nth row 0)
        desc (nth row 3)]
    (str "<td width=\"33%\" valign=\"top\" align=\"center\">"
         "<a href=\"" (demo-path name) "\">"
         "<img src=\"" (demo-path name) "\" width=\"300\" alt=\"" (escape desc) "\">"
         "</a><br><code>bb " name "</code><br>"
         "<sub>" (escape desc) "</sub></td>")))

(defn- group-block
  [group]
  (let [rows (get (reg/by-group) group)
        chunks (partition-all columns rows)]
    (str "#### " group " (" (count rows) ")\n\n"
         "<table>\n"
         (str/join "\n"
                   (map (fn [chunk]
                          (str "<tr>\n"
                               (str/join "\n" (map cell chunk))
                               ;; Pad the short final row so the remaining cells
                               ;; keep their width instead of stretching.
                               (str/join "" (repeat (- columns (count chunk))
                                                    "\n<td width=\"33%\"></td>"))
                               "\n</tr>"))
                        chunks))
         "\n</table>\n")))

(defn html
  "The whole gallery, marker to marker."
  []
  (str begin-marker "\n\n"
       (str/join "\n" (map group-block reg/groups))
       "\n" end-marker))

(defn splice
  "Replaces the marked region of README text. Returns nil if the markers are
  absent, so a caller can fail loudly rather than silently appending."
  [readme block]
  (let [b (str/index-of readme begin-marker)
        e (str/index-of readme end-marker)]
    (when (and b e (< b e))
      (str (subs readme 0 b) block (subs readme (+ e (count end-marker)))))))
